# ================ 应用基础配置 ================
spring:
  application:
    name: demo
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  # ================ 数据库配置 ================
  datasource:
    url: jdbc:mysql://localhost:3306/portmanagementsystem?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver


  # ================ Web服务器配置 ================
server:
  port: 8081
  servlet:
    context-path: /



# ================ MyBatis配置 ================
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.example.port_management_system.domain.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# ================ 日志配置 ================
logging:
  level:
    root: INFO
    com.example.port_management_system: DEBUG
    org.springframework.web: INFO
    org.mybatis: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

mybatis-plus:
  # 配置 XML 文件位置
  mapper-locations: classpath*:/mapper/**/*.xml
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: org.example.port_manage_system.entity
  configuration:
    # 开启驼峰命名自动映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 打印SQL日志